const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function runtime(fetch=async()=>({status:404,ok:false})){const c={fetch,Date,Promise,localStorage:{getItem:()=> 'test-only'},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary')};vm.createContext(c);for(const f of ['garden-data.js','md.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),c);return c;}
const json=x=>JSON.parse(JSON.stringify(x));
test('Markdown attribute injection and unsafe protocol',()=>{const c=runtime(),html=c.MD.render('[x](https://example.org/"onmouseover="alert)');assert.ok(html.includes('&quot;'));assert.ok(!html.includes('"onmouseover='));assert.ok(!c.MD.render('[x](javascript:alert)').includes('<a'));assert.ok(c.MD.render('[x](https://example.org)').includes('<a'));});
test('404 writes reject',async()=>{const c=runtime();await assert.rejects(c.GD.sync('now.json',{},l=>l),/404/);await assert.rejects(c.GD.pushPublic('user-articles.json',{articles:[]}),/404/);});
test('unconfirmed 200 write rejects',async()=>{const c=runtime(async(u,o)=>({status:o.method==='GET'?404:200,ok:o.method!=='GET',json:async()=>({})}));await assert.rejects(c.GD.sync('now.json',{},l=>l),/未确认/);});
test('resend keeps drafts and unpublished revisions private',()=>{const c=runtime(),all={draft:{id:'draft',body:'private'},p:{id:'p',body:'private revision',rev:2,pub:{body:'public',rev:1,updated:1}}},before=JSON.stringify(all),f=c.GD.publicationFile(all);assert.equal(f.articles.length,1);assert.equal(f.articles[0].body,'public');assert.equal(JSON.stringify(all),before);});
test('public merge preserves other devices and tombstones',()=>{const c=runtime(),m=c.GD.mergePublic({articles:[{id:'new',updated:2}],deletions:[{id:'deleted',updated:2}]},{articles:[{id:'other',updated:1},{id:'deleted',updated:1}]});assert.deepEqual(json(m.articles).map(x=>x.id),['new','other']);assert.equal(c.GD.mergePublic({articles:[{id:'deleted',updated:9}]},m).articles.length,2);});
test('409 retry uses new SHA and preserves newly remote article',async()=>{let gets=0,puts=0,last;const c=runtime(async(u,o)=>{if(o.method==='GET'){gets++;return {status:200,ok:true,json:async()=>({sha:'sha'+gets,content:Buffer.from(JSON.stringify({articles:[{id:'r'+gets,updated:1}]})).toString('base64')})};}puts++;last=JSON.parse(o.body);return puts===1?{status:409,ok:false}:{status:200,ok:true,json:async()=>({content:{sha:'done'},commit:{sha:'commit'}})};});await c.GD.pushPublic('user-articles.json',{articles:[{id:'mine',updated:2}]});assert.equal(last.sha,'sha2');assert.deepEqual(JSON.parse(Buffer.from(last.content,'base64').toString()).articles.map(x=>x.id),['mine','r2']);});
test('stale device cannot replace newer remote; conflict preserved',()=>{const c=runtime();let m=c.GD.mergeNow({day:{text:'old',updated:1}},{day:{text:'new',updated:2,_baseUpdated:1}});assert.equal(m.day.text,'new');m=c.GD.mergeNow({day:{text:'local',updated:3,_baseUpdated:1}},{day:{text:'remote',updated:2,_baseUpdated:1}});assert.ok(m.day._conflicts.some(x=>x.text==='remote'));});
test('local tombstone does not require storage side effect',()=>{assert.deepEqual(json(runtime().GD.mergeFragments({items:[],del:[1]},{items:[{t:1}],del:[]})),{items:[],del:[1]});});
